#!/bin/bash

x=1
n=ml
for e in "./hw5" "java XTest"
do
    for i in f j h k
    do
        while [ $x -lt 1000 ]
        do
            echo "$e $i $x" > "$n.$i.$x"
            time `$e $i $x` >> "$n.$i.$x"
            x=$(($x + 1))
        done
        x=1
    done
    n=jav
done
